services:
  front:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile_dev
    ports:
      - 4200:4200
    develop:
     watch:
       - path : ./package.json
         action : rebuild
       - path : ./angular.json
         action : rebuild
       - path : .
         target : /src
         action : sync

  front-prod:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: Dockerfile_prod
    ports:
      - 8080:80
    environment:
      - API_URL=${API_URL} # TODO: Change to API URL for production

networks:
  default:
    driver: bridge

volumes:
  tasked:
