name: Check Protected Files

# Déclenche le workflow sur chaque push ou pull request vers la branche de 'deployment'
on:
  push:
    branches:
      - ci/heroku_deployment
  pull_request:
    branches:
      - ci/heroku_deployment

jobs:
  check-protected-files:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Vérification des fichiers sensibles modifiés
      - name: Check if protected files are modified
        run: |
          # Liste des fichiers protégés (remplace par les chemins réels)
          PROTECTED_FILES="heroku.yml nginx.conf.template Dockerfile"

          # Vérifier les modifications dans les fichiers protégés
          if git diff --name-only HEAD^ | grep -q -E "$PROTECTED_FILES"; then
            echo "Modification des fichiers de configuration interdite."
            exit 1  # Échouer le workflow si des fichiers protégés sont modifiés
          else
            echo "Aucun fichier protégé n'a été modifié."
          fi
